### PR TITLE
Generate azure login certificate token

### PR DESCRIPTION
**Pull request by vittoriaThinkst**
## Proposed changes

Generate Azure Login Certificate 

https://github.com/thinkst/canarytokens/assets/126554007/ae02b84d-c8c5-4c0d-adb3-3cf721956388

### CODE REVIEW

**Comment by mclmax** [comment]
for this we should download it with the .pem extension or add it for folks when they generate the token i think?

**Review by mclmax — COMMENTED** [review]
let's just look at the `.pem` to the filename

**Comment by vittoriaThinkst** [comment]
yeah we can do that. I'm wondering why sometimes we get the extension from the backend, and sometimes we don't 🧐
Shouldn't we be consistent with the approach there?

**Comment by mclmax** [comment]
let's force em to add .pem or include it ourselves

**Review by mclmax — APPROVED** [review]

**Pull request merged**
