### PR TITLE
AWS SES Display email

### PR DESCRIPTION
**Pull request by Errahulaws**
## Proposed changes

Updating the WiKi for using `CANARY_ALERT_EMAIL_FROM_DISPLAY` in right format.

## Types of changes

What types of changes does your code introduce to this repository?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Lint and unit tests pass locally with my changes (if applicable)
- [ ] I have run pre-commit (`pre-commit` in the repo)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [x] Linked to the relevant github issue or github discussion

## Further comments

Updated WiKi as suggested in https://github.com/thinkst/canarytokens/pull/594

### CODE REVIEW

**Comment by Errahulaws** [comment]
@jacks0n9 Please have a look.

**Comment by jayjb** [comment]
@Errahulaws, would you mind emailing me at `jason [at] thinkst [dot] com` please? We would like to send you something for digging into this and finding an easy solution to an issue that more folks will no doubt bump into 😄

**Comment by jacks0n9** [comment]
> @jacks0n9 Please have a look.

why are you mentioning me? i think my only contribution to this repo has been fixing one typo

**Comment by Errahulaws** [comment]
> > @jacks0n9 Please have a look.
> 
> why are you mentioning me? i think my only contribution to this repo has been fixing one typo

Apology I guess I miss tagged.

**Comment by CybergalxU** [comment]
Hey stop emailing on this email. This is bullshit. Someone is fraudulently using this email account and it’s about to get shut down cuz I’m sick of seeing all this shitSent using the mail.com mail appOn 11/7/24 at 8:54 AM, Errahulaws wrote:
                
            
            
                
                    From: "Errahulaws" ***@***.***>Date: November 7, 2024To: "thinkst/canarytokens" ***@***.***>Cc: "Subscribed" ***@***.***>Subject: Re: [thinkst/canarytokens] AWS SES Display email (PR #604)
                
                


@jacks0n9 Please have a look.

why are you mentioning me? i think my only contribution to this repo has been fixing one typo

Apology I guess I miss tagged.

**Comment by Errahulaws** [comment]
> @Errahulaws, would you mind emailing me at `jason [at] thinkst [dot] com` please? We would like to send you something for digging into this and finding an easy solution to an issue that more folks will no doubt bump into 😄

@jayjb Sent an Email at give mail.

**Pull request merged**
