### PR TITLE
Made the alert throttling tuneable [Issue #72]

### PR DESCRIPTION
**Pull request by sqa-consulting**
Provides a configurable setting that removes the restriction on alerts per minute, which defaults to 1.

The default setting of 1 per minute makes perfect sense for emails but not all scenarios.

This was an issue for some of our implementations where we use webhooks to forward data into a SIEM and some events were not getting logged.

### CODE REVIEW

**Comment by sqa-consulting** [comment]
This has been tested using the docker method, with the two files simply swapped out in the Dockerfile.  

Tested with nothing set, 5 and 1000 and results are as expected.

Tested by generating webhooks into a simple Flask endpoint.

**Comment by sqa-consulting** [comment]
@jayjb

**Comment by jayjb** [comment]
Hi @sqa-consulting,

Ill be checking this today. Thanks for the PR. We have another fix coming in as well so both will be pushed today.

**Review by jayjb — APPROVED** [review]

**Comment by jayjb** [comment]
Hi @sqa-consulting,

Thanks for contributing to our project. We always happy to have folks working on it. Please email me at `jay [at] thinkst [dot] com` so that we can organise to send you something as a thanks!

**Pull request merged**
